const mongoose = require("mongoose");

const awsServiceOrderSchema = mongoose.Schema({
    cloud: String,
    ami: String,
    instance_type: String,
    name: String,
    key_name: String,
    monitoring: String,
    vpc_security_group_ids: String,
    subnet_id: String,
    cpu_core_count: String,
    cpu_threads_per_core: String,
    cpu_credits: String,
    disable_api_termination: String,
    kms_key_id: String,
    snapshot_id: String,
    source_dest_check: String,
    create_spot_instance: String,
    iam_instance_profile: String,
    ebs_optimized: String,
    enable_volume_tags: String,
    hibernation: String,
    ipv6_address_count: String,
    ipv6_addresses: String,
    launch_template: String,
    private_ip: String,
    tenancy: String,
    Environment: String,
    device_name: String,
    volume_type: String,
    volume_size: String,
    delete_on_termination: String,
    encrypted: String,
    iops: String,
    role_name: String,
    availability_zone: String,
    associate_public_ip_address: String,
    ApplicationName: String,
    ApplicationOwner: String,
    EmailID: String,
    Business: String,
    target_group_arn: String,
    target_id: String,
    port: String,
    status: String,
    approved: String,
    provisioned: String,
    order_created_at: String,
    provisioned_at: String,
    ec2_instance_id: String,
    ec2_public_ip: String,
    ec2_pem_path: String
});

module.exports = mongoose.model("awsserviceorder", awsServiceOrderSchema);